public class GetStockInChannelRequestWrapper {

    
    public String companyCode;
	public String initialDate;
	public String finalDate;
	public String initialCustomerCode;
	public String finalCustomerCode;
	public String I_SPART;
	public String I_VKORG;
	public String I_VTWEG;

	
	/*public static GetStockInChannelRequestWrapper parse(String json) {
		return (GetStockInChannelRequestWrapper) System.JSON.deserialize(json, GetStockInChannelRequestWrapper.class);

}*/	
}