public class SalesOrderTrackingInvoices {
    
    public string invoiceNumber;
    public string invoiceSeries;
    public string senderDocument;
    public string destinationDocument;
    public string carrierName;
    public string invoiceDate;
    public string cancellationDate;
    public string invoiceTotalValue;
    public string invoiceIdNumber;
    public string invoicekey;
    public string generalStatusOfTheInvoice;
    public string estimatedDeliveryDate;
    public string deliveryDate;
    public string sapOrderNumber;
     public string accId;
    public string SAPBillingDOC; // added by  GRZ(Javed)  08-03-2023  for RITM0514419
    public string Depot;// added by  GRZ(Javed)  08-03-2023  for RITM0514419

}