// const recordMetadata = {
//     name: 'name',
//     email: 'email',
//     website: 'url',
//     amount: 'currency',
//     phone: 'phoneNumber',
//     closeAt: 'dateInFuture',
// };

// export default function fetchDataHelper({ amountOfRecords }) {
//     return fetch('https://data-faker.herokuapp.com/collection', {
//         method: 'POST',
//         headers: {
//             'Content-Type': 'application/json; charset=utf-8',
//         },
//         body: JSON.stringify({
//             amountOfRecords,
//             recordMetadata,
//         }),
//     }).then(response => response.json());
// }
export default function fetchDataHelper(){
    
return [{
    Id:'1',
    Office__c:'office1', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'2',
    Office__c:'office2', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'3',
    Office__c:'office3', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'4',
    Office__c:'office4', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'5',
    Office__c:'office5', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'6',
    Office__c:'office6', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'7',
    Office__c:'office7', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'8',
    Office__c:'office8', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'9',
    Office__c:'office9', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'10',
    Office__c:'office10', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'11',
    Office__c:'office11', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'12',
    Office__c:'office12', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'13',
    Office__c:'office13', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'14',
    Office__c:'office14', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'15',
    Office__c:'office15', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'16',
    Office__c:'office16', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'17',
    Office__c:'office17', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'18',
    Office__c:'office18', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'19',
    Office__c:'office19', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
},
{
    Id:'20',
    Office__c:'office20', 
    Fiscal_Year__c:'fiscal', 
    Month__c:'month', 
    Distributor__c:'Distributor', 
    Pesticidal_Year__c:'Pesticidal year', 
    Single_pack_number__c:'single pack', 
    Region__c:'Region', 
    Area__c:'Area', 
    Material__c:'Material', 
    Single_Pack_Size__c:'Single pack', 
    Distributors_Office__c:'Distributors',
}
];
}